trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: UsePHPVersion@0
  inputs:
    versionSpec: '8.2'

- script: php -v
  displayName: 'Check PHP Version'

- script: composer --version
  displayName: 'Check Composer'

- script: echo "Build Success"
  displayName: 'Build Verification'